#!/usr/bin/env bash

env glide update

platforms=("linux/386" "linux/amd64" "linux/arm" "linux/arm64" "windows/amd64" "windows/386" "darwin/amd64")

for platform in "${platforms[@]}"
do
    platform_split=(${platform//\// })
    GOOS=${platform_split[0]}
    GOARCH=${platform_split[1]}
    output_name='vcom-'$GOOS'-'$GOARCH
    if [ $GOOS = "windows" ]; then
        output_name+='.exe'
    fi  

    flags="-w"

    echo $platform

    env GOOS=$GOOS GOARCH=$GOARCH go build -ldflags="$flags" -o $output_name vcom.go
    if [ $? -ne 0 ]; then
        echo 'An error has occurred! Aborting the script execution...'
        exit 1
    fi

done

env upx --brute vcom-*-*
